<?xml version="1.0" encoding="utf-8"?><Database Name="test" Class="MapDemoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=test;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="testConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LOCATION" Member="LOCATIONs">
    <Type Name="LOCATION">
      <Column Name="X" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MUC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATIONID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LOCATIONNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EMLOYEENAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IMG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>