<?xml version="1.0" encoding="utf-8"?><Database Name="QLHANG" Class="qlBangHangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.90;Initial Catalog=QLHANG;Persist Security Info=True;User ID=sa" SettingsObjectName="BanHang.Properties.Settings" SettingsPropertyName="QLHANGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHUHANG" Member="CHUHANGs">
    <Type Name="CHUHANG">
      <Column Name="MACHUHANG" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SODT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SOTK" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGANHANG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TIENQUY" Member="TIENQUYs">
    <Type Name="TIENQUY">
      <Column Name="TONGSOTIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_HOADON" Member="CT_HOADONs">
    <Type Name="CT_HOADON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHAP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MAHANG" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENHANG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SIZE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TRACHUHANG" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NHAPQUY" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_TIENQUY" Member="CT_TIENQUYs">
    <Type Name="CT_TIENQUY">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHUNGTU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NGAYCT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SODT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TRACHUHANG" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NHAPQUY" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHATKY_TIENQUY" Member="NHATKY_TIENQUYs">
    <Type Name="NHATKY_TIENQUY">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DUTRUOC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NGAYDU" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIENNHAP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="QUYNHAP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.USERS" Member="USERs">
    <Type Name="USER">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FULLNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ROLEID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHAP_HANG" Member="NHAP_HANGs">
    <Type Name="NHAP_HANG">
      <Column Name="MANHAP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CHUHANG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SODT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SOTK" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGANHANG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CHIETKHAU" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MAHANG" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TENHANG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SIZE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SLNHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SLBAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANHTOAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NGAYTHANHTOAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GHICHUTT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOINHUAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SLTAMTT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STTAMTT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GHICHUXUATHANG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>